# Form implementation generated from reading ui file 'voteApp.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(347, 286)
        self.voteButton = QtWidgets.QPushButton(parent=Dialog)
        self.voteButton.setGeometry(QtCore.QRect(90, 80, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.voteButton.setFont(font)
        self.voteButton.setObjectName("voteButton")
        self.idInput = QtWidgets.QLineEdit(parent=Dialog)
        self.idInput.setGeometry(QtCore.QRect(110, 60, 160,30))
        self.idInput.setObjectName("idInput")
        self.idInput.setFont(font)
        self.idLabel = QtWidgets.QLabel(parent=Dialog)
        self.idLabel.setGeometry(90,55,100,40)
        self.idLabel.setObjectName("idLabel")
        self.idLabel.setText("ID")
        font = QtGui.QFont()
        font.setPointSize(15)
        self.idLabel.setFont(font)
        self.idInput.setPlaceholderText('###-##-####')
        self.exitButton = QtWidgets.QPushButton(parent=Dialog)
        self.exitButton.setGeometry(QtCore.QRect(90, 160, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.topLabel = QtWidgets.QLabel(parent=Dialog)
        self.topLabel.setGeometry(QtCore.QRect(110, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.topLabel.setFont(font)
        self.topLabel.setObjectName("topLabel")
        self.voteJaneButton = QtWidgets.QPushButton(parent=Dialog)
        self.voteJaneButton.setGeometry(QtCore.QRect(90, 100, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.voteJaneButton.setFont(font)
        self.voteJaneButton.setAutoDefault(True)
        self.voteJaneButton.setObjectName("voteJaneButton")
        self.voteJohnButton = QtWidgets.QPushButton(parent=Dialog)
        self.voteJohnButton.setGeometry(QtCore.QRect(90, 160, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.voteJohnButton.setFont(font)
        self.voteJohnButton.setObjectName("voteJohnButton")
        self.bottomLabel = QtWidgets.QLabel(parent=Dialog)
        self.bottomLabel.setGeometry(QtCore.QRect(100, 230, 300, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.bottomLabel.setFont(font)
        self.bottomLabel.setObjectName("bottomLabel")
        self.johnLabel = QtWidgets.QLabel(parent=Dialog)
        self.johnLabel.setGeometry(QtCore.QRect(70, 120, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.johnLabel.setFont(font)
        self.johnLabel.setText("")
        self.johnLabel.setObjectName("johnLabel")
        self.janeLabel = QtWidgets.QLabel(parent=Dialog)
        self.janeLabel.setGeometry(QtCore.QRect(70, 80, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.janeLabel.setFont(font)
        self.janeLabel.setText("")
        self.janeLabel.setObjectName("janeLabel")
        self.totalLabel = QtWidgets.QLabel(parent=Dialog)
        self.totalLabel.setGeometry(QtCore.QRect(70, 160, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.totalLabel.setFont(font)
        self.totalLabel.setText("")
        self.totalLabel.setObjectName("totalLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.voteButton.setText(_translate("Dialog", "Vote"))
        self.exitButton.setText(_translate("Dialog", "Exit"))
        self.topLabel.setText(_translate("Dialog", "Vote Menu"))
        self.voteJaneButton.setText(_translate("Dialog", " Vote Jane"))
        self.voteJohnButton.setText(_translate("Dialog", " Vote John"))
        self.bottomLabel.setText(_translate("Dialog", " "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
